"""create initial schema

Revision ID: 50360f5b74f0
Revises:
Create Date: 2026-04-18 23:20:21.257922

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50360f5b74f0"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "passages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("difficulty", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("grammar_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("word_count", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "cognitive_skill_profiles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("grammar_level", sa.Integer(), nullable=False),
        sa.Column("vocabulary_tier", sa.Integer(), nullable=False),
        sa.Column("weak_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("strong_areas", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "motor_skill_profiles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("overall_wpm", sa.Float(), nullable=False),
        sa.Column("overall_accuracy", sa.Float(), nullable=False),
        sa.Column("key_profiles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("bigram_stats", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "typing_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("passage_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("keystrokes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["passage_id"],
            ["passages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # Indexes for common queries — not auto-generated by Alembic
    op.create_index("idx_motor_skill_user", "motor_skill_profiles", ["user_id"])
    op.create_index("idx_cognitive_skill_user", "cognitive_skill_profiles", ["user_id"])
    op.create_index(
        "idx_passage_difficulty",
        "passages",
        ["difficulty"],
        postgresql_using="gin",
    )
    op.create_index(
        "idx_passage_grammar_tags",
        "passages",
        ["grammar_tags"],
        postgresql_using="gin",
    )
    op.create_index(
        "idx_sessions_user_time",
        "typing_sessions",
        ["user_id", "completed_at"],
    )
    op.create_index(
        "idx_sessions_completed",
        "typing_sessions",
        ["user_id", "completed_at"],
        postgresql_where=sa.text("completed_at IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("typing_sessions")
    op.drop_table("motor_skill_profiles")
    op.drop_table("cognitive_skill_profiles")
    op.drop_table("users")
    op.drop_table("passages")
    # ### end Alembic commands ###
